### ISSUE TITLE
New (and future) resources not added to geojson

### ISSUE THREAD

**Issue by mattbeckley** [hobuinc/usgs-lidar#18]
Hello,

I was curious if the 99 resources that were added recently will have geojson boundaries added to the usgs-lidar/boundaries/geojson directory?    Currently the new additions are not added this directory.  In addition, will future resources be added to the geojson folder or will they only be written to the usgs-lidar/boundaries/ folder as 0.json, 1.json, etc. (JSON files with web-mercator coordinates) ??  Knowing the preferred convention will help with scripting to update my database when new resources are added.

Thanks!

**Comment by hobu** [comment]
@connormanning we need to figure something out to add the boundaries to automated output when we refresh.

**Comment by mattbeckley** [comment]
If it helps, I adapted one of the scripts in your util folder to do this task:

`import ogr
import osr
import glob
import json
import shutil
import os

web_mercator = osr.SpatialReference()
web_mercator.ImportFromEPSG(3857)

geographic = osr.SpatialReference()
geographic.ImportFromEPSG(4326)

#----------------------------------------------------------------------
def WriteIndividualJSON(jsonwild,outpath):
    #get a list of all original json files.
    for f in glob.glob(jsonwild):

        with open(f) as j:
            data = j.read()
        jload = json.loads(data)

        for key,item in jload.items():
            out_data = {key:jload[key]}

            #write out a single JSON per boundary...
            output = os.path.join(outpath, os.path.basename(key)+'.json')
            with open(output,'w') as j:
                json.dump(out_data, j)
#----------------------------------------------------------------------                

#----------------------------------------------------------------------                
def JSON2GEOJSON(jsonwild, outpath):
    for f in glob.glob(jsonwild):
        with open(f) as j:
            data = j.read()

        jload = json.loads(data)    
        for key,item in jload.items():

            #create the JSON format
            geo_in = '{"type": "MultiPolygon","coordinates":'+str(item)+'}'

            g = ogr.CreateGeometryFromJson(geo_in)

            g.AssignSpatialReference(web_mercator)
            g.TransformTo(geographic)
            geojson = g.ExportToJson()

            #write out geojson for each boundary
            output = os.path.join(outpath, os.path.basename(key)+'.json')
            with open(output,'wb') as j:
                j.write(geojson.encode('utf-8'))
#----------------------------------------------------------------------

                
#call routine to write out individual JSON files.  One per boundary.
#Right now they are lumped in 20 different files.
print("Writing out the individual JSON files..")
jsonwild = '../*.json'
outpath  = '../single'
WriteIndividualJSON(jsonwild,outpath)

#convert Individual files to GEOJSON...
print("Convert JSON to GEOJSON")
jsonwild_single = "../single/*.json")
outpath         = '../single/geojson'
JSON2GEOJSON(jsonwild_single,outpath)
`

**Comment by hobu** [comment]
https://github.com/hobu/usgs-lidar/blob/master/boundaries/resources.geojson should now be current but it is still a snapshot. We still need to make this run as a GitHub action on PR merges to refresh the catalog. It's quick to do and USGS is still pushing data.

**Comment by connormanning** [comment]
Closed via #27.
