### ISSUE TITLE
HTTPS and CORS

### ISSUE THREAD

**Issue by ghost** [hobuinc/usgs-lidar#22]
Not sure if this is the place to report this, but the S3 HTTPS endpoint doesn't include "Access-Control-Allow-Origin: *" like the HTTP one which prevents loading the data from HTTPS sites.
Would it be possible to enable CORS on the HTTPS endpoint?

**Comment by connormanning** [comment]
The bucket has this CORS policy set on it:
```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <AllowedHeader>Authorization</AllowedHeader>
</CORSRule>
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>HEAD</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <AllowedHeader>Authorization</AllowedHeader>
</CORSRule>
</CORSConfiguration>
```

Can you give a method to reproduce your issue where there are no CORS headers present?  For example, when I view one of the resources in Potree I have CORS headers:
<img width="1163" alt="Screen Shot 2020-05-02 at 1 26 28 PM" src="https://user-images.githubusercontent.com/5015470/80872622-a034cb00-8c78-11ea-8c73-16d15324dd40.png">

**Comment by ThatDan** [comment]
Ah, I was trying `https://s3-us-west-2.amazonaws.com/usgs-lidar-public/IA_FullState/ept.json` which I just realized isn't shown on https://usgs.entwine.io
I found it in https://github.com/hobu/usgs-lidar/blob/master/boundaries/resources.geojson though.

**Comment by ghost** [comment]
Strange. Was doing a simple fetch on https://s3-us-west-2.amazonaws.com/usgs-lidar-public/IA_FullState/ept.json in Chrome when I saw it.
<img width="1438" alt="Screen Shot 2020-05-02 at 11 44 07 AM" src="https://user-images.githubusercontent.com/25945984/80873096-00bd0b80-8c6b-11ea-9546-b8c3b8c1d97d.png">
Clearing my cache seemed to fix it, though.
