### ISSUE TITLE
Copying datasets from s3

### ISSUE THREAD

**Issue by ghost** [hobuinc/usgs-lidar#28]
I'm on an intermittent connection and was interested in locally processing/hosting a lidar dataset. Is the usgs-lidar-public bucket configured to allow copying?

aws s3 cp s3://usgs-lidar-public/USGS_LPC_CA_LosAngeles_2016_LAS_2018 . --recursive
fatal error: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied

ls operations are similarly denied:
aws s3 ls s3://usgs-lidar-public/
An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied

I have aws cli configured with my project's credentials, and am not sure it this interferes with accessing public s3 buckets. 

Alternatively, I've found a [web interface for the bucket](https://s3.console.aws.amazon.com/s3/buckets/usgs-lidar-public/USGS_LPC_CA_LosAngeles_2016_LAS_2018/?region=us-west-2&tab=overview), but don't see a way to download the entire directory from here.

Thanks for your work, and let me know if this wrong venue to ask about the public usgs s3 bucket access.

**Comment by hobu** [comment]
>  An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied

Nope. Use the RequesterPays bucket at `s3://usgs-lidar` if you want bulk access.

**Comment by hobu** [comment]
To add a bit more context here – AWS is providing public access to the `s3://usgs-lidar-public` bucket of data organized as [Entwine Point Tile](https://entwine.io/entwine-point-tile.html). To prevent "convenient" bulk fetches of the data via this mechanism, List is turned off. Users that want bulk access are encouraged to use the USGS bulk bucket at `s3://usgs-lidar` to list and fetch full-density tiles. `s3://usgs-lidar-public` is not a perfect mirror of the `s3://usgs-lidar` bucket, and it is going to contain more data than the EPT bucket as data is processed.

**Comment by ghost** [comment]
Thanks for clarifying.

**Comment by ghost** [comment]
Just double-checking, listing is enabled for the RequesterPays, s3://usgs-lidar bucket?

$ aws s3 ls s3://usgs-lidar --request-payer requester
An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied

**Comment by hobu** [comment]
Works for me with multiple AWS profiles

```
 aws s3 ls s3://usgs-lidar/Projects/ --request-payer requester
```

**Comment by ghost** [comment]
Thanks, that line errors for me, so is useful to know it's on my end. It's probably some misconfiguration (billing?) in my profile.

**Comment by hobu** [comment]
> billing

Yes, you'll need to have billing setup for it to charge you for hitting a RequesterPays bucket.

**Comment by ghost** [comment]
In case anyone else gets stuck here, my problem was the aws user did not have a S3 permission policy attached to it (AmazonS3FullAccess).

Thank you for your patience as I bungle through my first aws project here.
