### ISSUE TITLE
Problems with scale and offset in USGS_LPC_CA_LosAngeles_2016_LAS_2018/ept.json

### ISSUE THREAD

**Issue by kulpojke** [hobuinc/usgs-lidar#36]
I am trying to access data in the USGS_LPC_CA_LosAngeles_2016_LAS_2018 dataset using the ept.  I am getting the scale and offset for the dimensions from the schema of the top level ept.json.    When I apply the scale and offset to the coordinates of the box i wish to query and run the pipeline it runs very quickly and returns no points.  If I tinker with the coordinates by hand and make the box bigger I then get some returns.  Due to this, and other things I have done over the course of the last few days while trying to get it to work, I am fairly certain that after applying the scale and offsets the query box is very small, much smaller than a meter<sup>2</sup>.  Here is the workflow summarized again:

```
[bbox in EPSG:4326]  ---transform -->  [bbox in EPSG:3857]  ---scale/offset*-->  [bbox in ept scaled coordinates]
--pipeline usning readers.ept with bbox in ept scaled coordinates-->  empty return
```

* scale and offset applied as ```original_value * scale + offset```.

I am going crazy trying to get this to work, help would be greatly appreciated.

**Comment by connormanning** [comment]
This is a bit abstract.  Can you please supply an actual EPT reader pipeline specification that reproduces the behavior you are referring to?  What is the 4326 or 3857 bounds that you are interested in?

You should do not need to apply any scale/offset to your query bounds.  Unless you are supplying an SRS with your bounds, they should be presented in the native coordinate system of the data (in this case 3857).

**Comment by kulpojke** [comment]
This is the most recent version of the pipeline. 
```
[
    {
    "bounds": "([-13128140.232456215, -13128140.044853443], [3906024.568639325, 3906024.7244866122])",
    "filename": "https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_CA_LosAngeles_2016_LAS_2018/ept.json",
    "type": "readers.ept",
    "spatialreference":"EPSG:3857"
    },
    {
    "type": "filters.reprojection",
    "in_srs":"EPSG:3857",
    "out_srs": "EPSG:26911"
    },
    {
    "filename": "xxx.laz",
    "type": "writers.las"
    },
    {
    "filename": "xxx.tif",
    "bounds": "([-118.066863605, -118.066723605], [33.826110567, 33.826250567])",
    "gdalopts": "tiled=yes,     compress=deflate",
    "nodata": -9999,
    "output_type": "idw",
    "resolution": 1,
    "type": "writers.gdal",
    "window_size": 6
    }
]
```

The bounds for the ept reader come from:
```
# get the lat, lon of point from dataset
id = 1986759
lat = la.loc[la.ID==id]['LATITUDE'].values[0]
lon = la.loc[la.ID==id]['LONGITUDE'].values[0]

# make the bbox in EPSG:4326
[xmin, xmax], [ymin, ymax] = make_bbox(lat, lon)
    
# define transform from EPSG:4326 to EPSG:3857
old_crs = osr.SpatialReference() 
old_crs.ImportFromEPSG(4326) 
new_crs = osr.SpatialReference() 
new_crs.ImportFromEPSG(3857)
transform = osr.CoordinateTransformation(old_crs,new_crs)

# transform bbox points
ymin, xmin, zmin = transform.TransformPoint(ymin, xmin)
ymax, xmax, zmax = transform.TransformPoint(ymax, xmax)

# now rescale using the scale and offest from the ept.json
xmin, ymin = rescale(xmin, ymin)
xmax, ymax = rescale(xmax, ymax)
```
If I understand correctly, you are saying I can omit the last step above (rescale).  Is this correct?

Thanks

**Comment by connormanning** [comment]
I see a couple of problems from looking at your pipeline.

- Your bounds `[-13128140.232456215, -13128140.044853443], [3906024.568639325, 3906024.7244866122]` are approximately 20 centimeters in width, so even if there was data there, you'd be lucky to get even one point with this query.
- Even if you expand your bounds a bit, there is simply no data around that area: you can see a marker for your bounds on both the map and on the point cloud display here:
<img width="883" alt="Screen Shot 2021-01-29 at 9 54 29 AM" src="https://user-images.githubusercontent.com/5015470/106297218-166e5a00-6218-11eb-90ed-330123a68844.png">

In particular, your Y value of `3906024` is not within the Y range of the conforming bounds which have range `[3934094, 4140819]`, see the EPT metadata.

**Comment by kulpojke** [comment]
Thanks, for the  response.  I figured it out after you mentioned not using the offsets and scales.  There were a few problems that together were causing my confusions:
1) I did not need to use scale and offset.
2) In this bit of code:
```
# transform bbox points
ymin, xmin, zmin = transform.TransformPoint(ymin, xmin)
ymax, xmax, zmax = transform.TransformPoint(ymax, xmax)
```
It turns out the transform takes the args as (ymax, xmax (,zmax)), but returns them in the order xmax, ymax, zmax. So my x and y were mixed up.
3) the resolution on the gdal writer needed to me set to 1.  At 10 (which I don't know why I ever had it a 10 in the first place) the pixels were  to big to fit into the extent of the query, so the tiff was too big.

It works nicely now.  Thanks again.
