### ISSUE TITLE
Missing or corrupt files in FL_WestEvergladesNP_topobathymetric_2018

### ISSUE THREAD

**Issue by mattbeckley** [hobuinc/usgs-lidar#43]
Dataset, FL_WestEvergladesNP_topobathymetric_2018, seems to have some missing and/or corrupted underlying LAZ files.  Sample pipeline to reproduce the error:

```
{
    "pipeline": [{
        "type": "readers.ept",
        "filename": "https://s3-us-west-2.amazonaws.com/usgs-lidar-public/FL_WestEvergladesNP_topobathymetric_2018/ept.json",
        "bounds": "([-9052298.823836278, -9051731.47227985], [2976799.223211773,2977622.5867943484])"
    },
    {
        "type":"filters.reprojection",
        "in_srs":"EPSG:3857",
        "out_srs":"EPSG:32617"
    },{
        "type" : "writers.las",
        "filename": "points.laz",
        "a_srs": "EPSG:32617"
    }]}

```
Returns error: PDAL: readers.ept: Error reading tile: Could not read from s3-us-west-2.amazonaws.com/usgs-lidar-public/FL_WestEvergladesNP_topobathymetric_2018/ept-data/11-475-1791-1020.laz

Note that these errors only occur in certain parts of the dataset.  Other areas seem to be working fine.  

Also, when trying to get classifications for this dataset, you get similar errors:
`docker run pdal/pdal pdal info --stats --filters.stats.dimensions=Classification --filters.stats.count=Classification https://s3-us-west-2.amazonaws.com/usgs-lidar-public/FL_WestEvergladesNP_topobathymetric_2018/ept.json --readers.ept.resolution=50 --readers.ept.threads=12 > classifications.json`

Returns error: PDAL: readers.ept: Error reading tile: Could not read from s3-us-west-2.amazonaws.com/usgs-lidar-public/FL_WestEvergladesNP_topobathymetric_2018/ept-data/5-8-28-16.laz

**Comment by hobu** [comment]
I'll reach out to USGS to see if we can delete/repush.

**Comment by keythread** [comment]
This dataset should be reprocessed now.
