### ISSUE TITLE
Over 1000 files in /boundaries/geojson

### ISSUE THREAD

**Issue by bhuffman-usgs** [hobuinc/usgs-lidar#44]
Because there are over 1000 files in the geojson folder github excludes about 78 from being visible on the github website.  This isn't an issue if you actually pull from the repo to your local machine but it does cause problems with using the github API to view the 'tree' of the repository as files aren't listed in the 'tree'.  Another by-product of this is the .geojson maps built in the /boundaries directory are also missing said datasets that were excluded.  Below is an example of the missing SC_Savannah_PeeDee sites compared to the full list of sites shown on usgs.entwine.io (image 1: github boundary map, image 2: entwine boundary map for sc data)
![image](https://user-images.githubusercontent.com/40209416/153080552-b7054a5e-4655-4342-bab8-d60704eb8775.png)
![image](https://user-images.githubusercontent.com/40209416/153080623-c5ba98e8-cfa3-4231-a1e5-fe05036e9f9d.png)

A work around is to make two new folders in the /boundaries/geojson directory and place half the files in one and the other half in the other.

**Comment by hobu** [comment]
The GeoJSON file should be renderable in any other software like QGIS that's capable of rendering it. I do not want to change the layout or data structure to accommodate this github rendering limitation. Too much stuff already depends upon the boundaries file being updated daily at the location where it is.
