### ISSUE TITLE
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/NM_SouthEast_B6_2018/ept.json

### ISSUE THREAD

**Issue by saparajith** [hobuinc/usgs-lidar#45]
A New Mexico data or header is corrupt/empty. 
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/NM_SouthEast_B6_2018/ept.json
Hope you are able to fix it. Thank you

**Comment by hobu** [comment]
This data is being reviewed and will be repushed once complete
