### ISSUE TITLE
USGS surveys with no epts

### ISSUE THREAD

**Issue by abarclay06** [hobuinc/usgs-lidar#58]
Your project description explains that `s3://usgs-lidar-public` contains EPT resources mirroring many (but not all) of the resources in `s3://usgs-lidar`. We've come across a few of these surveys, for example: 
- s3://usgs-lidar/Projects/USGS_LPC_AL_25Co_B2_2017/laz/
- s3://usgs-lidar/Projects/USGS_LPC_LA_Bayou_Nezpique_B4_2018/laz/
- s3://usgs-lidar/Projects/USGS_LPC_LA_Bayou_Nezpique_B5_2018/laz/
- s3://usgs-lidar/Projects/USGS_LPC_LA_UpperDeltaPlain_2017_LAS_2018/laz/
- s3://usgs-lidar/Projects/USGS_LPC_UT_Central_QL2_2018_LAS_2019/laz/

I'm curious if there are plans to create epts for these (and all non-entwined USGS) datasets? And if so, is there an expected timeline?

Also, thank you for all of your work and providing this data publicly. The availability and ease of using this data is greatly appreciated!

**Comment by hobu** [comment]
Collections that didn't make it across during the initial automated conversion process were rejected for either failing metadata checks, missing information, or inconsistencies that could not be handled without manual intervention. 

We are available for consulting if you want to try to bring more of these collections forward that require manual intervention. Alternatively, if you want to create these EPT conversions yourself and want to place them in a public place, we can copy them to include them in the set.
