### ISSUE TITLE
Getting physical size of all datasets

### ISSUE THREAD

**Issue by Mortano** [hobuinc/usgs-lidar#63]
I'm looking for a quick estimate on the total size of all point clouds in this dataset. Not the number of points, but the physical size, either of the processed data or the original data, both are fine. Getting the size of the public bucket using the AWS CLI didn't work for me due to the very large number of files (for which a quick estimate would also be nice):

`aws s3 ls --no-sign-request s3://usgs-lidar-public --summarize --human-readable --recursive` seems to be the preferred command, but it lists all objects on the bucket which is terribly slow. No result after running this command for a few hours.

I also tried `aws cloudwatch get-metric-statistics` for the metric name `BucketSizeBytes`, but this fails with an `AccessDenied` error (`User: ... is not authorized to perform: cloudwatch:GetMetricStatistics because no identity-based policy allows the cloudwatch:GetMetricStatistics action`).

Neither the `ept.json` files, nor the JSON files in `ept-sources` contain information on the file sizes, so this also doesn't seem to be an option.

I was wondering if someone with root access to the bucket could get a size estimate. The AWS S3 Console (the web GUI, not the CLI) provides metrics, but I can't access those since I don't own the bucket. 

Any help would be appreciated.

**Comment by hobu** [comment]
> I was wondering if someone with root access to the bucket could get a size estimate.

Why? Are you looking to copy it somewhere? If you're doing that, you're doing it wrong.

**Comment by Mortano** [comment]
I'm writing my Ph.D. thesis and comparing different publicly available point cloud datasets. For that I need some numbers such as number of points (which the USGS overview page shows) and file size (which I could not determine myself).

**Comment by hobu** [comment]
![Screenshot 2023-06-27 at 10 07 13 AM](https://github.com/hobuinc/usgs-lidar/assets/87751/fc9f41bd-21cd-4983-acef-4fc92b4e22f9)

**Comment by Mortano** [comment]
That works, thanks!
