### ISSUE TITLE
Automatic data selection and download based on shapefile

### ISSUE THREAD

**Issue by Vicent-Ribas** [hobuinc/usgs-lidar#64]
Hello. First of all, thank you for putting this together, looks like an awesome project and way of making things more accessible. 

I don't really know if here is the best place to ask for this inquiry, but I would like to know if there is a way of doing what I am trying to do:

Say I have a shapefile, and I would like to download only the tiles that overlap that given shapefile, so search among the online repository and only select and download the ones that I am interested in. I know this can be done in the National Mapp App manually, but I will be doing this process multiple times (> 1000) and I was wondering if there is a way that I can "talk" with the online repository from my local machine to repeat that multiple times. Basically, to automatize what so far can be done manually in the National Mapp downloader app. 

Thank you very much!

**Comment by hobu** [comment]
https://github.com/hobuinc/usgs-lidar/blob/master/boundaries/resources.geojson and https://github.com/hobuinc/usgs-lidar/blob/master/boundaries/boundaries.topojson are updated nightly. Grab a copy of it and do your intersections.

**Comment by Vicent-Ribas** [comment]
Hi thank you very much for that. Just one more quick question, how can I get from those boundaries to the actual downloading links? Basically to a link like this: https://rockyweb.usgs.gov/vdelivery/Datasets/Staged/Elevation/LPC/Projects/SC_SavannahPeeDee_2019_B19/SC_SavannahPeeDee_6_2019/0_file_download_links.txt. I see that each of the boundaries of the geojson is the same that I can find in the USGS Lidar Explorer Map but it provides only a link to a ept.json file, from which I don't know how to access the actual files. Thank you again!

**Comment by Vicent-Ribas** [comment]
And also, there is no boundary directory of each of those individual tiles, am I right? So that I can select even more precisely which ones to download?

**Comment by hobu** [comment]
You can't. I thought you were looking for the footprints of usgs.entwine.io. If you are looking for the footprints of the individual tiles, that is a geopackage that is available on RockyFTP, but I don't have the link.

**Comment by Vicent-Ribas** [comment]
https://fsapps.nwcg.gov/gtac/CourseDownloads/Reimbursables/FY21/Lidar_Material/USGS_FTP_Data_Download.pdf I believe you ment this, thank you again. Just to make it clear for me, from the footprints you sent me above, I cannot access the individual links of individual tiles within each footprint, am I correct?

**Comment by Vicent-Ribas** [comment]
Hello @hobu. Sorry for any disturbance. I just have a question here: the jsons you posted, have a link to the ept.json from which I can access and download the data that overlays my given polygons, if I understood correctly this (https://pdal.io/en/latest/stages/readers.ept.html). However, if I want to filter for USGS LiDAR quality (e.g., QL1, QL2...) I still need to go to the 3DEP LiDAR explorer (https://apps.nationalmap.gov/lidar-explorer/#/) and check for a given specific resource which quality that is. There is no way of filter out, say, all the QL3 resources from that resources.geojson, and rather would have to be done manually. Is this correct? Thank you again.

**Comment by hobu** [comment]
correct. All the JSON provides is a link to the resource. You'll need to do your own filtering based on other parameters and the collection ID yourself.

**Comment by Vicent-Ribas** [comment]
Nevertheless, I see that in the National Map App explorer there if you click on a USGS resource, a table of atributes pops up with the information I need: 

![image](https://github.com/hobuinc/usgs-lidar/assets/86651851/37d57531-5455-43de-b66b-accfc36c5c8f)

Is there a way to access that table from some source? Thanks!

**Comment by mattbeckley** [comment]
I believe you can get some of that info from the WESM.gpkg file in https://prd-tnm.s3.amazonaws.com/index.html?prefix=StagedProducts/Elevation/metadata/

**Comment by Vicent-Ribas** [comment]
Yes, that is the file I needed. Thank you very much.

**Comment by Vicent-Ribas** [comment]
Just FYI, the "name" column in the resources.geojson file does not match the "workunit" column in the WESM.gpkg file. For example: USGS_LPC_AL_25Co_B4_2017 in the former vs. AL_25Co_B4_2017 in the latter.

**Comment by Vicent-Ribas** [comment]
Also, one issue that I have found is the following: If I take the WESM.gpkg and look at the boundaries of the "workunits", they do not match either with the boundaries of the resources.geojson "names", see image: 

![image](https://github.com/hobuinc/usgs-lidar/assets/86651851/2d02e362-00ff-4c03-8d3c-7cf5e24ad74a)

The red line is the boundary of the "workunit" and therefore the real LAZ data tiles for that "workunit" end there. But if we look at the boundaries of the "names", the black lines, two of the resources overlap (that is the area in between the two black lines). This implies that the geojson.names is yielding two different urls for one single area, an area that only corresponds with one "workunit" of the real LAZ boundaries from the WESM.gpkg. 

I just thought this was worth noticing. Especially because I am trying to get data from various parts and I have to filter by "workunit", and then look for the url from which to download it using the readers.ept. Thank you.
