### ISSUE TITLE
continuous curl failure

### ISSUE THREAD

**Issue by kwazineutin** [hobuinc/usgs-lidar#65]
I am trying to use Reader.ept to access data via a URL.

The URL works fine; I can visualize the number of points in the polygon. However, when I try to use a pipeline to access the points and generate a surface, I get a curl failure. I am using PDAL in a Jupyter Notebook using the code below.

################################################
for index, row in tiles_mec.iterrows():
    
    id = row ['tile_id']
    
    resolution = 1
    useful_classes = "Classification[0:6],Classification[17:17],Classification[9:9],Classification[10:10],Classification[11:11],Classification[2:2]"
    
    #fetch all points and create full dsm
    reader = pdl.Reader.ept(url, 
                         resolution=resolution, 
                         polygon = row['geometry'].wkt)
    rng = pdl.Filter.range(limits=useful_classes)
    z = pdl.Writer.gdal(out_fdsm + id +"_rfdsm_r1.tif", 
                    resolution=resolution, 
                    dimension="Z", 
                    data_type="float32", 
                    output_type="mean",
                    nodata=-9999)

    pipeline = reader | rng | z
    pipeline.execute()
#################################################
I keep getting curl failure errors, as shown in the image. Could the size of the polygon be a factor? Thanks for addressing this. 

<img width="228" alt="Capture" src="https://github.com/hobuinc/usgs-lidar/assets/44908872/f3261228-e495-4789-a06c-3969ef766661">

**Comment by hobu** [comment]
It is a bad message from PDAL. I think we suppressed it in PDAL 2.6.0.

What's happening is a timeout is reached and then PDAL is retrying again (and succeeding).

**Comment by kwazineutin** [comment]
I have been running the code for several hours and have less than 10% of the tiles. Is there a more practical way for creating DSM for large areas without downloading the points? I'd be happy to explore that. Thanks.

**Comment by hobu** [comment]
> I have been running the code for several hours and have less than 10% of the tiles

You will have to make requests in smaller chunks. PDAL does not parallelize operations for you. We are [available to hire](https://hobu.co/access.html) to help with designing such processing approaches.
