### ISSUE TITLE
South Carolina VCRS information missing

### ISSUE THREAD

**Issue by bhuffman-usgs** [hobuinc/usgs-lidar#69]
We've been building a utility that relies on the SC 3DEP data.  I wanted to perform a check to make sure the elevations were all in the same datum however upon inspection I've found quite a few datasets either missing their VCRS info in the ept-sources 0.json, 100.json, 200.json, etc. files.  Some datasets are even missing those files entirely within the ept-sources directory for the datasets.  Additionally, I can't make heads or tails of the elevation units, some VCRS's say meters some say feet.  I can provide the python script I wrote to extract some summary info if requested and I've included the summary files that show what I've found, mentioned above.

I'm wondering a next step forward.  If it's not feasible for these datasets to be "fixed" then I think on my end I'll just limit our utility from using data within the spatial boundaries of the problem datasets.
[ept_source_data_org.json](https://github.com/hobuinc/usgs-lidar/files/14060648/ept_source_data_org.json)
[fail_source_data_org.json](https://github.com/hobuinc/usgs-lidar/files/14060649/fail_source_data_org.json)
[fail_source_summary.txt](https://github.com/hobuinc/usgs-lidar/files/14060650/fail_source_summary.txt)

**Comment by hobu** [comment]
> were all in the same datum however upon inspection I've found quite a few datasets either missing their VCRS info in the ept-sources 0.json, 100.json, 200.json, etc. files

This is a consequence of the 3DEP organizational structure, especially for older data, and it is why we normalized the horizontal coordinate system to web mercator (much to many people's chagrin). We couldn't do anything with the vertical component, however, as it was never consistently labeled, as you've found. 

In the past, I have resorted to extracting samples of data and comparing it to SRTM to attempt to guess at what the vertical might be for a particular dataset. 

I'm closing this ticket, as it doesn't have much to do with the EPT data per se. Given your github handle says you're USGS, maybe you will have success routing this problem into the organization.

**Comment by cjcrosby** [comment]
FWIW, we did a deep dive on VCRS of 3DEP datasets as part of our work to [enable topographic differencing between overlapping collections](https://opentopography.org/news/3dep_noaa_differencing) in OpenTopography. In this [closed issue](https://github.com/hobuinc/usgs-lidar/issues/10) Howard provides a bit more detail on the challenges of handling VCRS in the initial conversion of 3DEP point cloud data to EPT. 

We compared the EPT resources in the 3DEP Amazon PDS with the source LAZ data and the 3DEP WESM (Work unit Extent Spatial Metadata) and used that comparison to do our best to determine the correct VCRS and Geoid. 

For your list, here's our conclusions:
SC_LexingtonCo_2010_x = NAVD88 - Geoid03 (Feet)
SC_SavannahPeeDee_x_2019 = NAVD88 height - Geoid18 (ftUS)
SC_Berkeley_B2_2016 = NAVD88 height - Geoid12B (ftUS)

For these six, there's no VCRS metadata available at any of the sources we reviewed, so we default to NAVD88 height - Geoid12A (meters):
USGS_LPC_SC_6County_Abbeville_2012_LAS_2017_x
USGS_LPC_SC_6County_Aiken_2012_LAS_2017_x
USGS_LPC_SC_6County_Barnwell_2012_LAS_2017_x
USGS_LPC_SC_6County_Calhoun_2012_LAS_2017_x
USGS_LPC_SC_6County_Edgefield_2012_LAS_2017_x
USGS_LPC_SC_6County_McCormick_2012_LAS_2017_x

We pushed this info to the 3DEP catalog in OpenTopography, so you can search via [the portal](https://portal.opentopography.org/datasets) (e.g., https://portal.opentopography.org/datasets?minX=-83.353238&minY=32.0346&maxX=-78.541087&maxY=35.215402&group=usgs) or our [catalog API](https://portal.opentopography.org/apidocs/#/Public/getOtCatalog) with "include_federated" set to true (e.g., https://portal.opentopography.org/API/otCatalog?productFormat=PointCloud&minx=-123.2&miny=44.8&maxx=-121.9&maxy=45.7&detail=false&outputFormat=xml&include_federated=true) if you'd like to see our determinations of VCRS for each 3DEP dataset.

**Comment by jstoker74** [comment]
Sorry, I know this is closed but you can find the WESM Chris mentioned here: https://rockyweb.usgs.gov/vdelivery/Datasets/Staged/Elevation/metadata/WESM.gpkg
