### ISSUE TITLE
New errors for update boundaries pipeline

### ISSUE THREAD

**Issue by bhuffman-usgs** [hobuinc/usgs-lidar#74]
It was recently noticed that the update boundaries that is automated for every day is now failing several lidar datasets for South Carolina that it had not before, many of which are critical to us.  Additionally, the update automation is being performed at 12pm which is odd vs 12am.

**Comment by bhuffman-usgs** [comment]
Kyle, just some context, the datasets in SC that were once fine have a pdal error labelled as "filters.expressionstats: Invalid 'where': Unknown dimension 'Withheld' in assignment".  It's not just SC though, it looks like the error file is riddled with them.  I don't remember if the error file was like that in the past.  Just some information to pass along.

**Comment by hobu** [comment]
That's a PDAL bug resulting from recent 2.8. Set the pin back to 2.7 and we will fix the bug
